sudo: required

language: node_js
node_js:
  - "0.12"

install:
  - npm install -g npm

before_script:
  - npm install -g gulp
  - npm install

script:
  - node --version
  - gulp tests:unit
  - gulp tests:lint
  - gulp tests:integration
